# Data Engineering Configuration

seed: 42
total_examples: 62000

splits:
  train: 0.90
  val: 0.05
  test: 0.05

sources:
  PersonaChat: 10000
  SPC: 15000
  CharacterCodex: 20000
  LIGHT: 12000
  EmpatheticDialogues: 5000
  # Skyrim: 22000  # Uncomment for classwork version

options:
  light_max_pairs: 12000
  ed_max_examples: 5000
  max_scenario_length: 400
  max_fact_length: 200
  max_turns_per_dialogue: 20
