# Fine-Tuning Configuration

model:
  name: "Qwen/Qwen2.5-3B-Instruct"
  load_in_4bit: true

lora:
  rank: 16
  alpha: 32
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
  dropout: 0.05

training:
  epochs: 3
  batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 0.0002
  max_seq_length: 512
  warmup_ratio: 0.03
  weight_decay: 0.01
  
  output_dir: "outputs/model"
  logging_steps: 10
  save_steps: 500
  eval_steps: 500
