# Evaluation Configuration

model_path: "../fine_tuning/outputs/model"
test_data: "../../data_engineering/data/processed/publishable/test.jsonl"

metrics:
  - schema_validity
  - persona_similarity
  - hallucination_rate
  - diversity
  - latency

human_eval:
  num_examples: 100
  annotators: 2

output_dir: "outputs"
